import { type Metadata } from 'next';
import HeaderLoader from '@/components/HeaderLoader';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SideNavBar from '@/components/ui/SideNavbar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <SideNavBar />

                <div className="ml-16 sm:ml-56">
                    <HeaderLoader />

                    <main className="p-6">{children}</main>
                </div>
            </body>
        </html>
    );
}
